# Generated by Django 3.1 on 2020-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_userpreferences")]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="data",
            field=models.JSONField(default=dict),
        )
    ]
