# Generated by Django 5.2.9 on 2025-12-20 14:56

import django.contrib.postgres.fields
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0004_auto_20210420_2144")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="allowed_ips",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=netfields.fields.CidrAddressField(max_length=43),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
