# Generated by Django 5.2.9 on 2025-12-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_token_object_permissions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tokenobjectpermission",
            new_name="users_token_content_687354_idx",
            old_name="users_token_content_e63c7b_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenobjectpermission",
            new_name="users_token_token_i_ea8fcc_idx",
            old_name="users_token_token_i_a1c6e4_idx",
        ),
        migrations.AddField(
            model_name="token",
            name="can_manage_permissions",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tokenobjectpermission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
