# Generated by Django 3.2.3 on 2021-06-05 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("webhooks", "0002_alter_webhook_id")]

    database_operations = [migrations.AlterModelTable("Webhook", "extras_webhook")]
    state_operations = [migrations.DeleteModel("Webhook")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
