---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
    - pip install poetry
    - poetry config virtualenvs.create false
    post_install:
    - poetry install --no-root --only docs
mkdocs:
  configuration: mkdocs.yaml
