---
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
    - pip install poetry
    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --no-root --only docs
mkdocs:
  configuration: mkdocs.yaml
