# Generated by Django 4.1.9 on 2023-05-11 20:26

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0010_migrate_tags"),
        ("devices", "0004_move_tags_to_extras"),
    ]

    operations = [
        migrations.AlterModelOptions(name="platform", options={"ordering": ("name",)}),
        migrations.AddField(
            model_name="configuration",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="configuration",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="platform",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
