# Generated by Django 4.2.11 on 2024-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0103_session_bfd"), ("devices", "0007_move_router")]

    operations = [
        migrations.AddField(
            model_name="router",
            name="communities",
            field=models.ManyToManyField(blank=True, to="peering.community"),
        ),
    ]
