# Generated by Django 5.0.14 on 2025-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("devices", "0008_router_communities")]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        )
    ]
