# Generated by Django 5.2.5 on 2024-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bgp", "0003_move_community"),
        ("devices", "0009_router_unique_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="router",
                    name="communities",
                    field=models.ManyToManyField(blank=True, to="bgp.community"),
                ),
            ],
        )
    ]
