# Generated by Django 4.1.8 on 2023-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0002_migrate_jobs")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
