# Generated by Django 3.2 on 2021-05-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0002_alter_jobresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=127, null=True, unique=True)),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
    ]
