# Generated by Django 3.2.3 on 2021-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("extras", "0003_webhook")]

    operations = [
        migrations.CreateModel(
            name="IXAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=2000, verbose_name="URL")),
                ("api_key", models.CharField(max_length=2000, verbose_name="API key")),
                (
                    "api_secret",
                    models.CharField(max_length=2000, verbose_name="API secret"),
                ),
                (
                    "identity",
                    models.CharField(
                        max_length=256,
                        help_text="Identity used to interact with the IX-API",
                    ),
                ),
            ],
            options={
                "verbose_name": "IX-API",
                "ordering": ["name", "url", "-created"],
            },
        ),
    ]
