# Generated by Django 3.2.11 on 2022-01-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0004_ixapi"),
    ]

    operations = [
        migrations.CreateModel(
            name="RipeIrr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
