# Generated by Django 4.1.8 on 2023-04-30 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("extras", "0007_ixapi_access_tokens")]

    operations = [migrations.DeleteModel(name="JobResult")]
