# Generated by Django 4.1.9 on 2023-05-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("extras", "0012_migrate_objectchanges")]

    operations = [
        migrations.AlterField(
            model_name="ixapi", name="name", field=models.CharField(max_length=100)
        ),
        migrations.AlterField(
            model_name="webhook",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
