# Generated by Django 4.1.9 on 2023-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("extras", "0013_models_normalisation")]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(model_name="tag", name="comments"),
    ]
