# Generated by Django 5.2.4 on 2025-07-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("extras", "0020_journalentry")]

    operations = [
        migrations.AlterModelOptions(
            name="ixapi",
            options={
                "ordering": ["name", "api_url", "-created"],
                "verbose_name": "IX-API",
            },
        ),
        migrations.RemoveConstraint(model_name="ixapi", name="unique_ixapi_url_key"),
        migrations.RenameField(model_name="ixapi", old_name="url", new_name="api_url"),
        migrations.AddConstraint(
            model_name="ixapi",
            constraint=models.UniqueConstraint(
                fields=("api_url", "api_key"), name="unique_ixapi_url_key"
            ),
        ),
    ]
