# Generated by Django 5.2.15 on 2026-06-25 20:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0021_ixapi_api_url_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("table", models.CharField(max_length=100, unique=True)),
                (
                    "columns",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_configs",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"ordering": ["table"]},
        ),
    ]
