# Generated by Django 4.1.9 on 2023-05-11 20:25

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("extras", "0010_migrate_tags"), ("bgp", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="relationship", options={"ordering": ("name",)}
        ),
        migrations.AddField(
            model_name="relationship",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relationship",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
