# Generated by Django 5.2.5 on 2024-11-23 00:00

import taggit.managers
from django.db import migrations, models

import bgp.fields


class Migration(migrations.Migration):
    dependencies = [
        ("bgp", "0002_models_normalisation"),
        ("extras", "0017_configcontext_export_data_source_file"),
        ("peering", "0107_autonomoussystem_bgpq_overrides"),
    ]

    operations = [
        # Table renamed from peering app
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Community",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated", models.DateTimeField(auto_now=True, null=True)),
                        ("local_context_data", models.JSONField(blank=True, null=True)),
                        ("description", models.CharField(blank=True, max_length=200)),
                        ("name", models.CharField(max_length=100, unique=True)),
                        ("slug", models.SlugField(max_length=100, unique=True)),
                        ("value", bgp.fields.CommunityField(max_length=50)),
                        (
                            "type",
                            models.CharField(
                                blank=True,
                                choices=[("egress", "Egress"), ("ingress", "Ingress")],
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "tags",
                            taggit.managers.TaggableManager(
                                help_text="A comma-separated list of tags.",
                                through="extras.TaggedItem",
                                to="extras.Tag",
                                verbose_name="Tags",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "communities",
                        "ordering": ["value", "name"],
                    },
                ),
            ],
        )
    ]
