# Generated by Django 5.2.11 on 2026-02-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bgp", "0003_move_community"), ("peering", "0108_move_community")]

    operations = [
        migrations.AddField(
            model_name="community",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this community can be published publicly or not",
            ),
        ),
    ]
