# Generated by Django 1.11.8 on 2018-01-01 20:38


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0002_auto_20180101_0203")]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        )
    ]
