# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 17:45


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0004_auto_20180121_2207")]

    operations = [
        migrations.RenameField(
            model_name="synchronization",
            old_name="number_of_objects",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="synchronization",
            name="added",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="synchronization",
            name="deleted",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
