# Generated by Django 2.1.4 on 2018-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Network = apps.get_model("peeringdb", "Network")
        db_alias = schema_editor.connection.alias
        Network.objects.using(db_alias).filter(info_prefixes4=-1).update(
            info_prefixes4=0
        )
        Network.objects.using(db_alias).filter(info_prefixes6=-1).update(
            info_prefixes6=0
        )

    def reverse_func(apps, schema_editor):
        Network = apps.get_model("peeringdb", "Network")
        db_alias = schema_editor.connection.alias
        Network.objects.using(db_alias).filter(info_prefixes4=0).update(
            info_prefixes4=-1
        )
        Network.objects.using(db_alias).filter(info_prefixes6=0).update(
            info_prefixes6=-1
        )

    dependencies = [("peeringdb", "0008_auto_20181212_2106")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
