# Generated by Django 2.2 on 2019-04-17 16:51

from django.db import migrations
import netfields.fields
import utils


class Migration(migrations.Migration):

    dependencies = [("peeringdb", "0009_auto_20181212_2322")]

    operations = [
        migrations.AlterField(
            model_name="networkixlan",
            name="ipaddr4",
            field=netfields.fields.InetAddressField(
                blank=True,
                max_length=39,
                null=True,
                validators=[utils.validators.AddressFamilyValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="ipaddr6",
            field=netfields.fields.InetAddressField(
                blank=True,
                max_length=39,
                null=True,
                validators=[utils.validators.AddressFamilyValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="prefix",
            field=netfields.fields.CidrAddressField(max_length=43),
        ),
    ]
