# Generated by Django 3.0.1 on 2020-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peeringdb", "0011_contact")]

    operations = [
        migrations.AddField(
            model_name="peerrecord",
            name="visible",
            field=models.BooleanField(blank=True, default=True),
        )
    ]
