# Generated by Django 3.1.6 on 2021-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeringdb", "0014_auto_20201208_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="floor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facility",
            name="suite",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="floor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="suite",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
