# Generated by Django 3.2.6 on 2021-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0018_auto_20210523_1204")]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="available_voltage_services",
            field=models.CharField(
                blank=True,
                choices=[
                    ("48 VDC", "48 VDC"),
                    ("120 VAC", "120 VAC"),
                    ("208 VAC", "208 VAC"),
                    ("240 VAC", "240 VAC"),
                    ("480 VAC", "480 VAC"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="diverse_serving_substations",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="property",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Owner", "Owner"),
                    ("Lessee", "Lessee"),
                ],
                max_length=27,
                null=True,
            ),
        ),
    ]
