# Generated by Django 3.2.8 on 2021-10-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0020_alter_facility_available_voltage_services")]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="region_continent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("North America", "North America"),
                    ("Asia Pacific", "Asia Pacific"),
                    ("Europe", "Europe"),
                    ("South America", "South America"),
                    ("Africa", "Africa"),
                    ("Australia", "Australia"),
                    ("Middle East", "Middle East"),
                ],
                max_length=255,
                null=True,
                verbose_name="Continental Region",
            ),
        ),
    ]
