# Generated by Django 3.2.9 on 2021-11-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0021_facility_region_continent")]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="sales_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="sales_phone",
            field=models.CharField(blank=True, max_length=192),
        ),
    ]
