# Generated by Django 4.0.6 on 2022-07-28 20:31

from django.db import migrations, models

import peeringdb.models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0023_auto_20220205_1347")]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="status_dashboard",
            field=peeringdb.models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="status_dashboard",
            field=peeringdb.models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="rir_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="rir_status_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="status_dashboard",
            field=peeringdb.models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
