# Generated by Django 4.1.8 on 2023-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0026_campus")]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
        migrations.AddField(
            model_name="carrier",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
        migrations.AddField(
            model_name="facility",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
        migrations.AddField(
            model_name="network",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_media",
            field=models.JSONField(blank=True, null=True, default=dict),
        ),
    ]
