# Generated by Django 4.2.8 on 2024-01-24 21:13

from django.db import migrations

import peeringdb.models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0027_social_media_field")]

    operations = [
        migrations.AddField(
            model_name="network",
            name="info_types",
            field=peeringdb.models.MultipleChoiceField(
                blank=True,
                choices=[
                    ("NSP", "NSP"),
                    ("Content", "Content"),
                    ("Cable/DSL/ISP", "Cable/DSL/ISP"),
                    ("Enterprise", "Enterprise"),
                    ("Educational/Research", "Educational/Research"),
                    ("Non-Profit", "Non-Profit"),
                    ("Route Server", "Route Server"),
                    ("Network Services", "Network Services"),
                    ("Route Collector", "Route Collector"),
                    ("Government", "Government"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="available_voltage_services",
            field=peeringdb.models.MultipleChoiceField(
                blank=True,
                choices=[
                    ("48 VDC", "48 VDC"),
                    ("120 VAC", "120 VAC"),
                    ("208 VAC", "208 VAC"),
                    ("240 VAC", "240 VAC"),
                    ("400 VAC", "400 VAC"),
                    ("480 VAC", "480 VAC"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
