# Generated by Django 5.0.6 on 2024-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0028_network_info_types")]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="bfd_support",
            field=models.BooleanField(default=False),
        ),
    ]
