# Generated by Django 5.0.9 on 2024-10-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0029_networkixlan_bfd_support")]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="ix_side",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ix_side_set",
                to="peeringdb.facility",
                verbose_name="IXP side",
            ),
        ),
        migrations.AddField(
            model_name="networkixlan",
            name="net_side",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="net_side_set",
                to="peeringdb.facility",
                verbose_name="Network side",
            ),
        ),
    ]
