# Generated by Django 5.2.5 on 2025-10-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peeringdb", "0031_created_update_fields")]

    operations = [
        migrations.CreateModel(
            name="HiddenPeer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("until", models.DateTimeField(blank=True, null=True)),
                (
                    "peeringdb_ixlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_peers",
                        to="peeringdb.ixlan",
                    ),
                ),
                (
                    "peeringdb_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_on",
                        to="peeringdb.network",
                    ),
                ),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["until", "peeringdb_network", "peeringdb_ixlan"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("peeringdb_network", "peeringdb_ixlan"),
                        name="network_ixlan_unique_hiddenpeer",
                    )
                ],
            },
        ),
    ]
