---
name: 🐛 Bug Report
description: Report a reproducible bug in the current release of Peering Manager
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for reporting _reproducible bugs_. If
        you're having trouble with installation or just looking for assistance
        with using Peering Manager, please visit our
        [discussion forum](https://github.com/peering-manager/peering-manager/discussions)
        instead.
  - type: input
    attributes:
      label: Peering Manager version
      description: >
        What version of Peering Manager are you currently running? (If you
        don't have access to the most recent release, consider testing on the
        [demo instance](https://demo.peering-manager.net/) before opening a
        bug report to see if your issue has already been addressed.)
      placeholder: v1.3.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Python version
      description: What version of Python are you currently running?
      options:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Describe in detail the steps for someone else to reproduce this bug
        using the current stable release of Peering Manager. If reporting a
        bug in the REST API, be sure to reconstruct the raw HTTP request(s)
        being made."
      placeholder: |
        1. Click on "Add" to create a session
        2. Set IP address to 192.0.2.1
        3. Click the "create" button
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The BGP session should be created and user redirected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed Behavior
      description: What happened instead?
      placeholder: A TypeError exception was raised
    validations:
      required: true
