---
name: 🚀 Feature Request
description: Propose a new Peering Manager feature or enhancement
labels: ["type: feature request"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for submitting well-formed proposals to
        extend or modify Peering Manager in some way. If you're trying to
        solve a problem but can't figure out how, or if you still need time to
        work on the details of a proposed new feature, please start a
        [discussion](https://github.com/peering-manager/peering-manager/discussions)
        instead.
  - type: input
    attributes:
      label: Peering Manager version
      description: What version of Peering Manager are you currently running?
      placeholder: v1.3.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Feature type
      options:
        - Data model extension
        - New functionality
        - Change to existing functionality
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed functionality
      description: >
        Describe in detail the new feature or behaviour you'd like to propose.
        Include any specific changes to work flows, data models, or the user
        interface.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: >
        Explain how adding this functionality would benefit other users.
        What need does it address?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Database changes
      description: >
        Note any changes to the database schema necessary to support the new
        feature. For example, does the proposal require adding a new model or
        field? (Not all new features require database changes.)
  - type: textarea
    attributes:
      label: External dependencies
      description: >
        List any new dependencies on external libraries or services that this
        new feature would introduce. For example, does the proposal require
        the installation of a new Python package? Please keep in mind that we
        do not want to add to many extra dependencies.
        (Not all new features introduce new dependencies.)
