# Generated by Django 4.0.6 on 2022-08-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messaging", "0002_email")]

    operations = [
        migrations.AlterField(
            model_name="contact", name="name", field=models.CharField(max_length=100)
        ),
    ]
