# Generated by Django 4.1.9 on 2023-06-16 20:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0010_migrate_tags"),
        ("messaging", "0003_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="contactrole",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
