# Generated by Django 4.1.9 on 2023-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messaging", "0004_move_tags_to_extras")]

    operations = [
        migrations.AlterModelOptions(
            name="contactrole", options={"ordering": ("name",)}
        ),
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contact",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactrole",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="email",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
