# Generated by Django 4.2.11 on 2024-03-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_datasource_and_datafile"),
        ("messaging", "0005_models_normalisation"),
    ]

    operations = [
        migrations.AlterModelOptions(name="email", options={}),
        migrations.AddField(
            model_name="email",
            name="auto_synchronisation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic synchronisation of data when the data file is updated",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="data_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.datafile",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="data_path",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Path to the remote file, relative to its data source root",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Remote data source",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.datasource",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="data_synchronised",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
