# Generated by Django 3.2.4 on 2021-06-24 12:16

import django.db.models.deletion
from django.db import migrations, models

from net.models import Connection


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0075_auto_20210604_1709"),
        ("net", "0001_initial"),
    ]

    def deleted_orphaned_connections(apps, schema_editor):
        connections = Connection.objects.all()
        for connection in connections:
            if not connection.internet_exchange_point:
                print(
                    f"Deleting Orphaned Connection: {connection} - {connection.ipv4_address}/{connection.ipv6_address}"
                )
                connection.delete()

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="internet_exchange_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peering.internetexchange",
            ),
        ),
        migrations.RunPython(deleted_orphaned_connections),
    ]
