# Generated by Django 3.2.6 on 2021-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("net", "0002_alter_connection_internet_exchange_point")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="config_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
