# Generated by Django 4.0.6 on 2022-08-06 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("net", "0004_rename_config_context_connection_local_config_context")
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={"ordering": ["internet_exchange_point", "router"]},
        ),
    ]
