# Generated by Django 4.0.6 on 2022-08-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("net", "0005_alter_connection_options")]

    operations = [
        migrations.RenameField(
            model_name="connection", old_name="state", new_name="status"
        ),
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("maintenance", "Maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=20,
            ),
        ),
    ]
