# Generated by Django 4.0.8 on 2023-01-07 16:51

import netfields.fields
from django.db import migrations

import utils.validators


class Migration(migrations.Migration):
    dependencies = [("net", "0006_rename_state_connection_status")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="mac_address",
            field=netfields.fields.MACAddressField(
                blank=True,
                null=True,
                validators=[utils.validators.MACAddressValidator],
                verbose_name="MAC address",
            ),
        ),
    ]
