# Generated by Django 4.2.3 on 2023-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("net", "0008_move_tags_to_extras")]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=20,
            ),
        ),
    ]
