# Generated by Django 5.0.5 on 2024-05-18 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("net", "0010_move_router_to_devices_stage_1"),
        ("peering", "0103_move_router_to_devices_stage_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="connection", name="router"),
        migrations.RenameField(
            model_name="connection", old_name="devices_router", new_name="router"
        ),
    ]
