# Generated by Django 5.2.15 on 2026-08-02 20:37

import django.db.models.functions.comparison
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("net", "0011_add_bfd")]

    operations = [
        migrations.CreateModel(
            name="PrefixListEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("prefix", netfields.fields.CidrAddressField(max_length=43)),
                ("exact", models.BooleanField(default=False)),
                ("greater_equal", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("less_equal", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IRR prefix",
                "verbose_name_plural": "IRR prefixes",
                "ordering": ("prefix",),
                "constraints": [
                    models.UniqueConstraint(
                        models.F("prefix"),
                        models.F("exact"),
                        django.db.models.functions.comparison.Coalesce("greater_equal", 0),
                        django.db.models.functions.comparison.Coalesce("less_equal", 0),
                        name="net_prefixlistentry_unique",
                    )
                ],
            },
        ),
    ]
