# Object change log actions
OBJECT_CHANGE_ACTION_CREATE = 1
OBJECT_CHANGE_ACTION_UPDATE = 2
OBJECT_CHANGE_ACTION_DELETE = 3
OBJECT_CHANGE_ACTION_CHOICES = (
    (OBJECT_CHANGE_ACTION_CREATE, "Created"),
    (OBJECT_CHANGE_ACTION_UPDATE, "Updated"),
    (OBJECT_CHANGE_ACTION_DELETE, "Deleted"),
)

# User Actions Constants
USER_ACTION_CREATE = 1
USER_ACTION_EDIT = 2
USER_ACTION_DELETE = 3
USER_ACTION_IMPORT = 4
USER_ACTION_BULK_DELETE = 5
USER_ACTION_BULK_EDIT = 6
USER_ACTION_CHOICES = (
    (USER_ACTION_CREATE, "created"),
    (USER_ACTION_EDIT, "modified"),
    (USER_ACTION_DELETE, "deleted"),
    (USER_ACTION_IMPORT, "imported"),
    (USER_ACTION_BULK_DELETE, "bulk deleted"),
    (USER_ACTION_BULK_EDIT, "bulk modified"),
)
