version: '3.7'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: peering_manager
      POSTGRES_USER: devbox
      POSTGRES_PASSWORD: devbox
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
