# Generated by Django 3.1 on 2020-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("utils", "0006_auto_20200626_2340")]

    operations = [
        migrations.AlterField(
            model_name="objectchange",
            name="object_data",
            field=models.JSONField(editable=False),
        )
    ]
