# Generated by Django 3.2.5 on 2021-07-21 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("utils", "0008_auto_20210420_2144")]

    operations = [
        migrations.RenameField(
            model_name="objectchange", old_name="action", new_name="old_action"
        )
    ]
