# Generated by Django 3.2.5 on 2021-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("utils", "0010_auto_20210721_1415")]

    operations = [
        migrations.RemoveField(model_name="objectchange", name="old_action"),
        migrations.AlterField(
            model_name="objectchange",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
