# Generated by Django 3.2.13 on 2022-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("utils", "0012_tag_ordering")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
