# Generated by Django 4.1.9 on 2023-06-16 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("extras", "0010_migrate_tags"), ("utils", "0013_alter_tag_slug")]

    operations = [
        migrations.AlterIndexTogether(
            name="taggeditem",
            index_together=None,
        ),
        migrations.RemoveField(
            model_name="taggeditem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="taggeditem",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="TaggedItem",
        ),
    ]
