WEBHOOK_HTTP_METHOD_GET = "GET"
WEBHOOK_HTTP_METHOD_POST = "POST"
WEBHOOK_HTTP_METHOD_PUT = "PUT"
WEBHOOK_HTTP_METHOD_PATCH = "PATCH"
WEBHOOK_HTTP_METHOD_DELETE = "DELETE"
WEBHOOK_HTTP_METHOD_CHOICES = (
    (WEBHOOK_HTTP_METHOD_GET, "GET"),
    (WEBHOOK_HTTP_METHOD_POST, "POST"),
    (WEBHOOK_HTTP_METHOD_PUT, "PUT"),
    (WEBHOOK_HTTP_METHOD_PATCH, "PATCH"),
    (WEBHOOK_HTTP_METHOD_DELETE, "DELETE"),
)
WEBHOOK_HTTP_CONTENT_TYPE_JSON = "application/json"
