# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peering", "0002_auto_20170820_1809")]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="ipv4_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="ipv6_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="configuration_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peering.ConfigurationTemplate",
            ),
        ),
    ]
