# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0007_auto_20171202_1900")]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="peeringdb_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
