# Generated by Django 2.0.4 on 2018-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0011_auto_20180329_2146")]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="check_bgp_session_states",
            field=models.BooleanField(
                default=False,
                help_text="If enabled with a usable router, the state of peeringsessions belonging to this IX will be fetched.",
            ),
        ),
        migrations.AddField(
            model_name="peeringsession",
            name="bgp_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idle", "Idle"),
                    ("connect", "Connect"),
                    ("active", "Active"),
                    ("opensent", "OpenSent"),
                    ("openconfirm", "OpenConfirm"),
                    ("established", "Established"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
