# Generated by Django 2.1.3 on 2018-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0021_auto_20181113_2136")]

    operations = [
        migrations.RemoveField(
            model_name="directpeeringsession", name="export_routing_policy"
        ),
        migrations.RemoveField(
            model_name="directpeeringsession", name="import_routing_policy"
        ),
        migrations.RemoveField(
            model_name="internetexchange", name="export_routing_policy"
        ),
        migrations.RemoveField(
            model_name="internetexchange", name="import_routing_policy"
        ),
        migrations.RemoveField(
            model_name="internetexchangepeeringsession", name="export_routing_policy"
        ),
        migrations.RemoveField(
            model_name="internetexchangepeeringsession", name="import_routing_policy"
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="export_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_export_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="import_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_import_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="export_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_export_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="import_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_import_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="export_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_export_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="import_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_import_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
    ]
