# Generated by Django 2.1.4 on 2019-01-05 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peering",
            "0026_autonomoussystem_potential_internet_exchange_peering_sessions",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="potential_internet_exchange_peering_sessions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
