# Generated by Django 2.1.4 on 2019-01-05 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peering",
            "0026_autonomoussystem_potential_internet_exchange_peering_sessions",
        )
    ]

    def forwards_func(apps, schema_editor):
        AutonomousSystem = apps.get_model("peering", "AutonomousSystem")
        db_alias = schema_editor.connection.alias
        AutonomousSystem.objects.using(db_alias).filter(
            potential_internet_exchange_peering_sessions=None
        ).update(potential_internet_exchange_peering_sessions=[])

    def reverse_func(apps, schema_editor):
        AutonomousSystem = apps.get_model("peering", "AutonomousSystem")
        db_alias = schema_editor.connection.alias
        AutonomousSystem.objects.using(db_alias).filter(
            potential_internet_exchange_peering_sessions=[]
        ).update(potential_internet_exchange_peering_sessions=None)

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="potential_internet_exchange_peering_sessions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
