# Generated by Django 2.1.4 on 2019-01-14 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("peering", "0028_internetexchangepeeringsession_is_router_server")]

    operations = [
        migrations.AlterModelOptions(
            name="internetexchange",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "view_configuration",
                        "Can view Internet Exchange's configuration",
                    ),
                    (
                        "deploy_configuration",
                        "Can deploy Internet Exchange's configuration",
                    ),
                ],
            },
        )
    ]
