# Generated by Django 2.1.4 on 2019-01-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peering", "0029_auto_20190114_2141")]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peering.Router",
            ),
        )
    ]
