# Generated by Django 2.1.7 on 2019-02-27 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("peering", "0030_directpeeringsession_router")]

    operations = [
        migrations.AlterModelOptions(
            name="directpeeringsession",
            options={"ordering": ["autonomous_system", "ip_address"]},
        ),
        migrations.AlterModelOptions(
            name="internetexchangepeeringsession",
            options={"ordering": ["autonomous_system", "ip_address"]},
        ),
    ]
