# Generated by Django 2.1.7 on 2019-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0031_auto_20190227_2210")]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("junos", "Juniper JUNOS"),
                    ("iosxr", "Cisco IOS-XR"),
                    ("ios", "Cisco IOS"),
                    ("nxos", "Cisco NX-OS"),
                    ("eos", "Arista EOS"),
                    ("", "Other"),
                ],
                help_text="The router platform, used to interact with it",
                max_length=50,
            ),
        )
    ]
