# Generated by Django 2.2 on 2019-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0035_auto_20190311_2334")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact E-mail"
            ),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="contact_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
