# Generated by Django 2.2 on 2019-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0038_auto_20190412_2233")]

    operations = [
        migrations.AddField(
            model_name="routingpolicy",
            name="address_family",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "All"), (4, "IPv4"), (6, "IPv6")], default=0
            ),
        )
    ]
