# Generated by Django 2.2 on 2019-04-17 16:51

import django.contrib.postgres.fields
import netfields.fields
from django.db import migrations

import utils


class Migration(migrations.Migration):
    dependencies = [("peering", "0039_routingpolicy_address_family")]

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="potential_internet_exchange_peering_sessions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=netfields.fields.InetAddressField(max_length=39),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="directpeeringsession",
            name="ip_address",
            field=netfields.fields.InetAddressField(max_length=39),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="ipv4_address",
            field=netfields.fields.InetAddressField(
                blank=True,
                max_length=39,
                null=True,
                validators=[utils.validators.AddressFamilyValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="ipv6_address",
            field=netfields.fields.InetAddressField(
                blank=True,
                max_length=39,
                null=True,
                validators=[utils.validators.AddressFamilyValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="ip_address",
            field=netfields.fields.InetAddressField(max_length=39),
        ),
    ]
