# Generated by Django 2.2 on 2019-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0040_auto_20190417_1851")]

    operations = [
        migrations.AlterField(
            model_name="routingpolicy",
            name="type",
            field=models.CharField(
                choices=[
                    ("export-policy", "Export"),
                    ("import-policy", "Import"),
                    ("import-export-policy", "Import+Export"),
                ],
                default="import-policy",
                max_length=50,
            ),
        )
    ]
