# Generated by Django 2.2 on 2019-05-09 12:39

from django.db import migrations
import peering.fields


class Migration(migrations.Migration):

    dependencies = [("peering", "0041_auto_20190430_1743")]

    operations = [
        migrations.AlterField(
            model_name="directpeeringsession",
            name="multihop_ttl",
            field=peering.fields.TTLField(
                blank=True,
                default=1,
                help_text="Use a value greater than 1 for BGP multihop sessions",
                verbose_name="Multihop TTL",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="multihop_ttl",
            field=peering.fields.TTLField(
                blank=True,
                default=1,
                help_text="Use a value greater than 1 for BGP multihop sessions",
                verbose_name="Multihop TTL",
            ),
        ),
    ]
