# Generated by Django 2.2.1 on 2019-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0043_router_use_netbox")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="export_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_export_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="import_routing_policies",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_import_routing_policies",
                to="peering.routingpolicy",
            ),
        ),
    ]
