# Generated by Django 2.2.2 on 2019-07-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peering", "0047_auto_20190619_1434")]

    operations = [
        migrations.RenameModel(old_name="ConfigurationTemplate", new_name="Template"),
        migrations.AddField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[("configuration", "Configuration"), ("email", "E-mail")],
                default="configuration",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="configuration_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peering.Template",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="configuration_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peering.Template",
            ),
        ),
    ]
