# Generated by Django 2.2.2 on 2019-08-06 06:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('peering', '0049_auto_20190731_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchange',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
