# Generated by Django 2.2.6 on 2019-10-31 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("peering", "0053_auto_20190921_2000")]

    operations = [
        migrations.AlterModelOptions(
            name="autonomoussystem",
            options={
                "ordering": ["asn"],
                "permissions": [("send_email", "Can send e-mails to AS contact")],
            },
        )
    ]
