# Generated by Django 3.0 on 2020-01-03 23:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("peering", "0055_auto_20191110_1312")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="prefixes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, editable=False, null=True
            ),
        )
    ]
