# Generated by Django 2.2.8 on 2019-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0055_auto_20191110_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='napalm_args',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_timeout',
            field=models.PositiveIntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
