# Generated by Django 2.2.8 on 2019-12-12 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0055_auto_20191110_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='napalm_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_timeout',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='The maximum time to wait for a connection in seconds'),
        ),
        migrations.AddField(
            model_name='router',
            name='napalm_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
