# Generated by Django 3.0.5 on 2020-05-09 14:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0056_autonomoussystem_prefixes")]

    operations = [
        migrations.AlterModelOptions(
            name="bgpgroup",
            options={"ordering": ["name", "slug"], "verbose_name": "BGP group"},
        ),
        migrations.AlterModelOptions(
            name="internetexchange", options={"ordering": ["name", "slug"]}
        ),
        migrations.AddField(
            model_name="router",
            name="napalm_args",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="router",
            name="napalm_password",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="router",
            name="napalm_timeout",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="router",
            name="napalm_username",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
