# Generated by Django 2.2.8 on 2019-12-06 20:22
  
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0056_auto_20191206_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='napalm_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
