# Generated by Django 3.0.6 on 2020-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0057_auto_20200509_1629")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="name_peeringdb_sync",
            field=models.BooleanField(default=True),
        )
    ]
