# Generated by Django 3.0.8 on 2020-07-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0058_autonomoussystem_name_peeringdb_sync")]

    operations = [
        migrations.AddField(
            model_name="router",
            name="last_deployment_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        )
    ]
