# Generated by Django 3.1 on 2020-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0061_community_slug")]

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="prefixes",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="router",
            name="napalm_args",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
