# Generated by Django 3.1.1 on 2020-09-13 14:12

from django.conf import settings
from django.db import migrations, models, transaction
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0063_auto_20200807_1503"),
    ]

    @transaction.atomic()
    def set_local_autonous_system(apps, schema_editor):
        db_alias = schema_editor.connection.alias

        my_asn = getattr(settings, "MY_ASN", None)
        if my_asn is None:
            # First setup, old MY_ASN setting is not used
            return

        # Get AS or create it with placeholders
        AutonomousSystem = apps.get_model("peering", "AutonomousSystem")
        try:
            my_asn = AutonomousSystem.objects.using(db_alias).get(asn=my_asn)
        except AutonomousSystem.DoesNotExist:
            my_asn = AutonomousSystem.objects.using(db_alias).create(
                asn=my_asn,
                name="[[REPLACE ME]]",
                comments="Auto-generated during multi-AS support migration",
                affiliated=True,
            )

        # Set local AS for direct sessions
        DirectPeeringSession = apps.get_model("peering", "DirectPeeringSession")
        DirectPeeringSession.objects.using(db_alias).update(
            local_autonomous_system=my_asn
        )

        # Same thing for IXPs
        InternetExchange = apps.get_model("peering", "DirectPeeringSession")
        InternetExchange.objects.using(db_alias).update(local_autonomous_system=my_asn)

    operations = [
        migrations.AlterModelOptions(
            name="autonomoussystem",
            options={
                "ordering": ["asn", "affiliated"],
                "permissions": [("send_email", "Can send e-mails to AS contact")],
            },
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="affiliated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="local_autonomous_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directpeeringsession_local_autonomous_system",
                to="peering.autonomoussystem",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="local_autonomous_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peering.autonomoussystem",
            ),
        ),
        migrations.RunPython(set_local_autonous_system),
        migrations.RemoveField(
            model_name="directpeeringsession",
            name="local_asn",
        ),
    ]
