# Generated by Django 3.1.4 on 2020-12-12 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb", "0014_auto_20201208_1856"),
        ("peering", "0065_auto_20201025_2137"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autonomoussystem",
            name="potential_internet_exchange_peering_sessions",
        ),
        migrations.RemoveField(
            model_name="internetexchange",
            name="peeringdb_id",
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="peeringdb_ix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peeringdb.internetexchange",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="peeringdb_netixlan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peeringdb.networkixlan",
            ),
        ),
    ]
