# Generated by Django 3.1.6 on 2021-02-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
        ("peering", "0067_auto_20210112_1318"),
    ]

    operations = [
        migrations.RemoveField(model_name="router", name="platform"),
        migrations.AddField(
            model_name="router",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                help_text="The router platform, used to interact with it",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="devices.platform",
            ),
        ),
    ]
