# Generated by Django 3.1.5 on 2021-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0067_auto_20210112_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="device_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("maintenance", "Maintenance"),
                ],
                help_text="State of the device for configuration pushes",
                max_length=20,
            ),
        ),
    ]
