# Generated by Django 3.1.7 on 2021-03-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0070_remove_router_last_deployment_id")]

    operations = [
        migrations.RemoveField(model_name="internetexchange", name="ipv4_address"),
        migrations.RemoveField(model_name="internetexchange", name="ipv6_address"),
        migrations.RemoveField(
            model_name="internetexchange", name="peeringdb_netixlan"
        ),
        migrations.RemoveField(model_name="internetexchange", name="peeringdb_ix"),
        migrations.RemoveField(model_name="internetexchange", name="router"),
        migrations.AddField(
            model_name="internetexchange",
            name="peeringdb_ixlan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peeringdb.ixlan",
            ),
        ),
        migrations.AlterModelOptions(
            name="internetexchangepeeringsession",
            options={"ordering": ["autonomous_system", "ixp_connection", "ip_address"]},
        ),
        migrations.RemoveField(
            model_name="internetexchangepeeringsession",
            name="internet_exchange",
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="ixp_connection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="net.connection",
            ),
        ),
    ]
