# Generated by Django 3.2 on 2021-04-27 00:39

import uuid

from django.db import migrations


def generate_service_reference(apps, schema_editor):
    model = apps.get_model("peering", "InternetExchangePeeringSession")
    for row in model.objects.all():
        if row.ixp_connection.internet_exchange_point is not None:
            asn = row.ixp_connection.internet_exchange_point.local_autonomous_system.asn
            row.service_reference = "IX{0}-{1}S".format(
                asn, uuid.uuid4().hex[:6].upper()
            )
            row.save(update_fields=["service_reference"])

    model = apps.get_model("peering", "DirectPeeringSession")
    for row in model.objects.all():
        asn = row.local_autonomous_system.asn
        row.service_reference = "D{0}-{1}S".format(asn, uuid.uuid4().hex[:6].upper())
        row.save(update_fields=["service_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0074_auto_20210426_1943"),
    ]

    operations = [
        migrations.RunPython(generate_service_reference, reverse_code=migrations.RunPython.noop),
    ]
