# Generated by Django 3.2.4 on 2021-06-13 07:36

from django.db import migrations, models
from peering.models.models import AutonomousSystem


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0075_auto_20210604_1709'),
    ]

    def sync_peering_policy(apps, schema_editor):
        # Resync all ASNs to update Peering Policy
        autonomous_systems = AutonomousSystem.objects.all()
        for autonomous_system in autonomous_systems:
            autonomous_system.synchronize_with_peeringdb()

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='general_policy',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Selective', 'Selective'), ('Restrictive', 'Restrictive'), ('No', 'No')], max_length=50, null=True, verbose_name='General Peering Policy'),
        ),
        migrations.RunPython(sync_peering_policy),
    ]
