# Generated by Django 3.2 on 2021-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0075_backfill_service_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directpeeringsession",
            name="service_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional: Internal Service Reference (will auto generate if left blank)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="service_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional: Unique Internal Service Reference (will auto generate if left blank)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
