# Generated by Django 3.2.4 on 2021-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0076_autonomoussystem_communities")]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="device_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("maintenance", "Maintenance"),
                ],
                default="enabled",
                help_text="State of the device for configuration pushes",
                max_length=20,
            ),
        ),
    ]
