# Generated by Django 3.2.7 on 2021-09-20 13:23

from django.db import migrations, models

import net.fields


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0077_alter_router_device_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="interface",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="vlan",
            field=net.fields.VLANField(blank=True, null=True, verbose_name="VLAN"),
        ),
    ]
