# Generated by Django 3.2.8 on 2021-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0077_alter_router_device_state")]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="jinja2_lstrip",
            field=models.BooleanField(
                default=False, help_text="Strips whitespaces before block"
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="jinja2_trim",
            field=models.BooleanField(
                default=False, help_text="Removes new line after tag"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="jinja2_lstrip",
            field=models.BooleanField(
                default=False, help_text="Strips whitespaces before block"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="jinja2_trim",
            field=models.BooleanField(
                default=False, help_text="Removes new line after tag"
            ),
        ),
    ]
