# Generated by Django 3.2.9 on 2021-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0078_template_trim_lstrip")]

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="ipv4_max_prefixes",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="IPv4 max prefix"
            ),
        ),
        migrations.AlterField(
            model_name="autonomoussystem",
            name="ipv6_max_prefixes",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="IPv6 max prefix"
            ),
        ),
    ]
