# Generated by Django 3.2.3 on 2021-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0004_ixapi"),
        ("peering", "0079_auto_nullable_max_prefix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internetexchange",
            options={
                "ordering": ["local_autonomous_system", "name", "slug"],
                "permissions": [
                    (
                        "view_internet_exchange_point_ixapi",
                        "Can view IX-API related info (read-only)",
                    ),
                    (
                        "change_internet_exchange_point_ixapi",
                        "Can use IX-API to change info (read-write)",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="ixapi_endpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="URL and authentication details to interact with IX-API",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="extras.ixapi",
                verbose_name="IX-API",
            ),
        ),
        migrations.AlterField(
            model_name="directpeeringsession",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("private-peering", "Private Peering"),
                    ("transit-provider", "Transit Provider"),
                    ("customer", "Customer"),
                ],
                max_length=50,
            ),
        ),
    ]
