# Generated by Django 3.2.11 on 2022-01-07 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("peering", "0082_move_autonomoussystem_contacts")]

    database_operations = [migrations.AlterModelTable("Email", "messaging_email")]
    state_operations = [migrations.DeleteModel("Email")]

    def cleanup_object_changes(apps, schema_editor):
        ContentType = apps.get_model("contenttypes", "ContentType")
        Email = apps.get_model("peering.Email")
        EmailType = ContentType.objects.get_for_model(Email)
        ObjectChange = apps.get_model("utils.ObjectChange")

        ObjectChange.objects.using(schema_editor.connection.alias).filter(
            changed_object_type=EmailType
        )._raw_delete(schema_editor.connection.alias)

    operations = [
        migrations.RunPython(cleanup_object_changes, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        ),
    ]
