# Generated by Django 3.2.11 on 2022-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0085_delete_configuration")]

    operations = [
        migrations.AddConstraint(
            model_name="directpeeringsession",
            constraint=models.UniqueConstraint(
                fields=(
                    "local_autonomous_system",
                    "autonomous_system",
                    "local_ip_address",
                    "ip_address",
                    "relationship",
                ),
                name="unique_directpeeringsession_as_ip_relationship",
            ),
        ),
    ]
