# Generated by Django 3.2.11 on 2022-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peering",
            "0086_directpeeringsession_unique_directpeeringsession_as_ip_relationship",
        )
    ]

    operations = [
        migrations.RemoveField(model_name="bgpgroup", name="bgp_session_states_update"),
        migrations.RemoveField(model_name="bgpgroup", name="check_bgp_session_states"),
        migrations.RemoveField(
            model_name="internetexchange", name="bgp_session_states_update"
        ),
        migrations.RemoveField(
            model_name="internetexchange", name="check_bgp_session_states"
        ),
        migrations.AddField(
            model_name="router",
            name="poll_bgp_sessions_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="router",
            name="poll_bgp_sessions_state",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Enable polling of BGP sessions state",
                verbose_name="Poll BGP sessions state",
            ),
        ),
    ]
