# Generated by Django 3.2.12 on 2022-02-10 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "peering",
            "0088_internetexchangepeeringsession_unique_internetexchangepeeringsession_connection_ip",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="directpeeringsession",
            name="unique_directpeeringsession_as_ip_relationship",
        ),
    ]
