# Generated by Django 3.2.13 on 2022-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peering",
            "0089_remove_directpeeringsession_unique_directpeeringsession_as_ip_relationship",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("egress", "Egress"), ("ingress", "Ingress")],
                max_length=50,
                null=True,
            ),
        ),
    ]
