# Generated by Django 4.0.4 on 2022-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0090_alter_community_type")]

    operations = [
        migrations.RenameField(
            model_name="router",
            old_name="config_context",
            new_name="local_context_data",
        ),
        migrations.RenameField(
            model_name="routingpolicy",
            old_name="config_context",
            new_name="local_context_data",
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bgpgroup",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="local_context_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
