# Generated by Django 3.2.13 on 2022-06-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peering", "0090_alter_community_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="bgp_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peering.bgpgroup",
                verbose_name="BGP group",
            ),
        ),
    ]
