# Generated by Django 4.0.6 on 2022-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0092_add_session_ixp_bgpgroup_status")]

    operations = [
        migrations.RemoveField(
            model_name="directpeeringsession",
            name="enabled",
        ),
        migrations.RemoveField(
            model_name="internetexchangepeeringsession",
            name="enabled",
        ),
        migrations.RenameField(
            model_name="router", old_name="device_state", new_name="status"
        ),
        migrations.AlterField(
            model_name="router",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("maintenance", "Maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
    ]
