# Generated by Django 4.0.8 on 2022-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0093_remove_session_enabled_and_rename_router_state")]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="use_netbox",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Use NetBox as proxy for NAPALM",
                verbose_name="Use NetBox",
            ),
        ),
    ]
