# Generated by Django 4.1.7 on 2023-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0094_alter_router_use_netbox")]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="communities",
            field=models.ManyToManyField(blank=True, to="peering.community"),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="communities",
            field=models.ManyToManyField(blank=True, to="peering.community"),
        ),
        migrations.AddField(
            model_name="routingpolicy",
            name="communities",
            field=models.ManyToManyField(blank=True, to="peering.community"),
        ),
    ]
