# Generated by Django 4.1.9 on 2023-06-16 20:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0010_migrate_tags"),
        ("peering", "0095_communities_sessions_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autonomoussystem",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="bgpgroup",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="directpeeringsession",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="routingpolicy",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="extras.TaggedItem",
                to="extras.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
