# Generated by Django 4.1.9 on 2023-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0096_move_tags_to_extras")]

    operations = [
        migrations.RemoveField(model_name="bgpgroup", name="comments"),
        migrations.RemoveField(model_name="community", name="comments"),
        migrations.RemoveField(model_name="internetexchange", name="comments"),
        migrations.RemoveField(model_name="routingpolicy", name="comments"),
        migrations.AddField(
            model_name="autonomoussystem",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="bgpgroup",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="router",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="routingpolicy",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="autonomoussystem",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bgpgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="bgpgroup",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="routingpolicy",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="routingpolicy",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
