# Generated by Django 4.2.3 on 2023-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0097_models_normalisation")]

    operations = [
        migrations.AlterField(
            model_name="bgpgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="directpeeringsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("provisioning", "Provisioning"),
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                    ("decommissioning", "Decommissioning"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("provisioning", "Provisioning"),
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                    ("decommissioning", "Decommissioning"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("pre-maintenance", "Pre-maintenance"),
                    ("maintenance", "Maintenance"),
                    ("post-maintenance", "Post-maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="enabled",
                max_length=50,
            ),
        ),
    ]
