# Generated by Django 4.2.7 on 2023-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0099_bgp_session_passive")]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="accepted_prefix_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="accepted_prefix_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
