# Generated by Django 5.0.5 on 2024-05-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_router"),
        ("peering", "0101_router_config_push_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="configuration_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="devices.configuration",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="local_autonomous_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="peering.autonomoussystem",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                help_text="The router platform, used to interact with it",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="devices.platform",
            ),
        ),
        migrations.AddField(
            model_name="directpeeringsession",
            name="devices_router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devices.router",
            ),
        ),
    ]
