# Generated by Django 5.0.9 on 2024-09-21 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("net", "0011_add_bfd"), ("peering", "0102_move_router")]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="bfd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="net.bfd",
            ),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="bfd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="net.bfd",
            ),
        ),
    ]
