# Generated by Django 5.0.13 on 2025-03-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0103_session_bfd")]

    operations = [
        migrations.AlterField(
            model_name="directpeeringsession",
            name="service_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional internal service reference",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchangepeeringsession",
            name="service_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional internal service reference",
                max_length=255,
                null=True,
            ),
        ),
    ]
