# Generated by Django 5.0.9 on 2024-11-01 22:11

from django.db import migrations, models

import peering.fields


class Migration(migrations.Migration):
    dependencies = [("peering", "0103_session_bfd")]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="value",
            field=models.CharField(
                max_length=50, validators=[peering.fields.validate_bgp_community]
            ),
        ),
    ]
