# Generated by Django 5.0.5 on 2024-05-18 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_router"),
        ("peering", "0103_move_router_to_devices_stage_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="directpeeringsession", name="router"),
        migrations.RenameField(
            model_name="directpeeringsession",
            old_name="devices_router",
            new_name="router",
        ),
        migrations.DeleteModel(name="Router"),
    ]
