# Generated by Django 5.0.14 on 2025-04-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net", "0011_add_bfd"),
        ("peering", "0104_loosen_service_reference_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="net.connection",
                verbose_name="Network connection on which this session lives",
            ),
        )
    ]
