# Generated by Django 5.2.3 on 2025-06-20 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0105_directpeeringsession_connection")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="as_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                editable=False,
                size=None,
            ),
        )
    ]
