# Generated by Django 5.2.5 on 2025-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0106_autonomoussystem_as_list")]

    operations = [
        migrations.AddField(
            model_name="autonomoussystem",
            name="retrieve_as_list",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="retrieve_prefixes",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="irr_sources_override",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="irr_ipv4_prefixes_args_override",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="autonomoussystem",
            name="irr_ipv6_prefixes_args_override",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
