# Generated by Django 5.2.11 on 2026-02-22 19:44

import uuid

import django.db.models.deletion
import netfields.fields
import taggit.managers
from django.db import migrations, models

import peering.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0021_ixapi_api_url_field"),
        ("peering", "0108_move_community"),
        ("peeringdb", "0033_hiddenpeer_peeringdb_fk_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeeringRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("local_context_data", models.JSONField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requesting_asn", peering.fields.ASNField()),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                ("request_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("decision_comment", models.TextField(blank=True)),
                (
                    "bfd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="net.bfd",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bgp.relationship",
                    ),
                ),
                (
                    "local_autonomous_system",
                    models.ForeignKey(
                        limit_choices_to={"affiliated": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peering_requests",
                        to="peering.autonomoussystem",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": [
                    ("review_peering_request", "Can review peering requests")
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestedSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("ip_address", netfields.fields.InetAddressField(max_length=39)),
                ("wants_password", models.BooleanField(default=False)),
                ("wants_bfd", models.BooleanField(default=False)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("rejection_comment", models.TextField(blank=True)),
                (
                    "created_session_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_session_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "internet_exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peering.internetexchange",
                    ),
                ),
                (
                    "peering_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_sessions",
                        to="peering.peeringrequest",
                    ),
                ),
                (
                    "peeringdb_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peeringdb.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["peering_request", "internet_exchange", "ip_address"],
            },
        ),
    ]
