# Generated by Django 5.2.15 on 2026-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peering", "0109_peeringrequest_requestedsession")]

    operations = [
        migrations.AddField(
            model_name="directpeeringsession",
            name="bgp_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="bgp_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
