CONTACT_ROLE_ABUSE = "Abuse"
CONTACT_ROLE_MAINTENANCE = "Maintenance"
CONTACT_ROLE_POLICY = "Policy"
CONTACT_ROLE_TECHNICAL = "Technical"
CONTACT_ROLE_NOC = "NOC"
CONTACT_ROLE_PUBLIC_RELATIONS = "Public Relations"
CONTACT_ROLE_SALES = "Sales"
CONTACT_ROLE_CHOICES = (
    (CONTACT_ROLE_ABUSE, "Abuse"),
    (CONTACT_ROLE_MAINTENANCE, "Maintenance"),
    (CONTACT_ROLE_POLICY, "Policy"),
    (CONTACT_ROLE_TECHNICAL, "Technical"),
    (CONTACT_ROLE_NOC, "NOC"),
    (CONTACT_ROLE_PUBLIC_RELATIONS, "Public Relations"),
    (CONTACT_ROLE_SALES, "Sales"),
)

CONTACT_VISIBILITY_PRIVATE = "Private"
CONTACT_VISIBILITY_USERS = "Users"
CONTACT_VISIBILITY_PUBLIC = "Public"
CONTACT_VISIBILITY_CHOICES = (
    (CONTACT_VISIBILITY_PRIVATE, "Private"),
    (CONTACT_VISIBILITY_USERS, "Users"),
    (CONTACT_VISIBILITY_PUBLIC, "Public"),
)
